signoff/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from signoff import views


app_name = 'signoff'
urlpatterns = [
    url(
        r'^$',
        views.index,
        name='signoff_index',
    ),
    url(
        r'^view/(?P<id>[\d]+)/?$',
        views.view_document,
        name='signoff_document',
    ),
]

signoff/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, Q, Prefetch
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel


class DocumentConsent(TimeStampedModel):
    document = models.ForeignKey('Document',
                                 related_name="consents",
                                 on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    ip = models.GenericIPAddressField(
        help_text=_("The IP address from which the document was signed."),
    )

    xff_header = models.CharField(
        max_length=255,
        null=True, blank=True,
        help_text=_("The X-Forwarded-For header sent when the document was "
                    "signed."),
    )

    signed_name = models.TextField(
        help_text=_("The name entered in the signature box when the user "
                    "signed this document."),
    )

    class Meta:
        unique_together = (("document", "user", "signed_name"), )


class DocumentQuerySet(models.QuerySet):
    def only_active(self):
        return self.filter(
            Q(next_version__isnull=True) |
            Q(next_version__required_by__gt=timezone.now())
        )

    def with_user(self, user):
        """
        Prefeteches DocumentConsent objects for the specified user to the
        key "user_consents".
        """

        kwargs = {}
        if hasattr(settings, 'SIGNOFF_CHECK_DOCUMENT_UPDATED') and\
           settings.SIGNOFF_CHECK_DOCUMENT_UPDATED:
            kwargs['created__gte'] = F('document__modified')
        if hasattr(settings, 'SIGNOFF_CHECK_FULL_NAME') and\
           settings.SIGNOFF_CHECK_FULL_NAME:
            kwargs['signed_name'] = user.get_full_name()

        # I think this is wrong - this doesn't check the document that the
        # consents are linked to. We want to use some sort of annotate, I
        # think.
        return self.prefetch_related(Prefetch(
            "consents",
            queryset=DocumentConsent.objects.filter(
                user=user,
                **kwargs
            ),
            to_attr="user_consents",
        ))


class Document(TimeStampedModel):
    code = models.CharField(
        max_length=16,
        help_text=_("A short code, like 'tos' or 'privacy', used to identify "
                    "the various types of documents."),
    )

    prev_version = models.OneToOneField(
        "Document",
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name='next_version',
        help_text=_("The previous revision of this document. Only the most "
                    "recent revision of each document code will be active at "
                    "any given time."),
    )

    name = models.CharField(
        max_length=255,
        help_text=_("Name of this document."),
    )

    details = models.TextField(
        help_text=_("A description of this document, about one paragraph "
                    "in length. Explain what the document is, and why the "
                    "user should review it."),
    )

    text = models.TextField(
        help_text=_("The text of this document, HTML is OK."),
    )

    required_by = models.DateTimeField(
        help_text=_("The time that this document must be signed by. After "
                    "this date, the document will be considered 'required' "
                    "by the django-consent middleware, and logged-in users "
                    "will need to sign it before being able to browse your "
                    "site."),
    )

    order = models.IntegerField(
        default=1000,
        help_text=_('An integer used to sort the list of Documents'),
    )

    objects = DocumentQuerySet.as_manager()

    def __str__(self):
        return '%s (#%d)' % (self.name, self.id)

    class Meta:
        ordering = ['order']
        unique_together = (('code', 'prev_version'), )

signoff/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from signoff.models import Document, DocumentConsent


def index(request):
    context = {}
    if request.user.is_authenticated:
        documents = Document.objects.with_user(request.user)
    else:
        documents = Document.objects

    context['documents'] = documents.all()
    context['current_documents'] = documents.only_active()

    return render(request, 'signoff/index.html', context)


@login_required
def view_document(request, id):
    document = get_object_or_404(Document.objects.with_user(request.user),
                                 id=id)

    context = {}
    context['document'] = document

    if document.user_consents:
        context['consent'] = document.user_consents[0]

    if request.method == 'POST':
        # Only record the signature if we don't already have one for this user
        if not document.user_consents:
            is_valid = True
            if not request.POST.get('consent_checkbox'):
                is_valid = False
                context['checkbox_error'] = True
            if request.POST.get('name') != request.user.get_full_name():
                is_valid = False
                context['name_error'] = True
            if is_valid:
                consent = DocumentConsent(
                    document=document,
                    user=request.user,
                    ip=request.META.get('REMOTE_ADDR'),
                    xff_header=request.META.get('HTTP_X_FORWARDED_FOR'),
                    signed_name=request.POST.get('name'),
                )
                consent.save()
            else:
                return render(request, 'signoff/document.html', context)


        return redirect('signoff:signoff_index')

    return render(request, 'signoff/document.html', context)

signoff/templates/signoff/base.html
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

signoff/templates/signoff/document.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ document.name }}
{% endblock %}

{% block content_title %}
    {{ document.name }}
{% endblock %}

{% block content %}

<p>{{ document.details }}</p>

{{ document.text|safe }}

{% if request.user.is_authenticated %}
<h2>{% trans "Signature" %}</h2>

{% if document.user_consents %}
    {% blocktrans with name=document.user_consents.0.signed_name date=document.user_consents.0.created %}
        Signed on {{ date }} by {{ name }}
    {% endblocktrans %}
{% else %}
    {% blocktrans %}
        If you agree with the terms above, please complete the form below.
    {% endblocktrans %}
    <form method="post" action="">{% csrf_token %}<fieldset>
        <dl>
            <dt>
                {% trans "Digital Signature" %}
                {% if name_error %}
                    <br><span class="error">{% trans "Your signature could not be accepted. The name you signed did not match your user account's display name." %}</span>
                {% endif %}
            </dt>
            <dd>
                <input type="text" name="name"><br>
                {{ request.user.get_full_name }}
            </dd>
        </dl>
        <dl>
            <dt>
                {% trans "Have you read and understood this document, and do you agree to be bound by it?" %}
                {% if checkbox_error %}
                    <br><span class="error">{% trans "Your signature could not be accepted. You did not agree to sign this document." %}</span>
                {% endif %}
            </dt>
            <dd><input type="checkbox" name="consent_checkbox">{% trans "I agree" %}</dd>
        </dl>
    </fieldset>
    <input type="submit" value="{% trans "I agree" %}">
    </form>
{% endif %}

{% endif %}

{% endblock %}

signoff/templates/signoff/email_body.html
{{ user.get_full_name }},

This message is to provide you a record of a document that you have reviewed
and agreed to. The details are below:

Document: {{ document.name }}
{{ document.details }}
Signed by: {{ user.get_full_name }} (username: {{ user.username }})
Signed on: {{ instance.created }}

For your reference, the document text is available below.

If you have any questions, please utilize your usual support channels. This
mail may not have been sent from a mailbox that is able to receive replies.

----

{{ document.text }}

signoff/templates/signoff/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Review Documents" %}
{% endblock %}

{% block content_title %}
    {% trans "Review Documents" %}
{% endblock %}

{% block content %}

<p>
{% blocktrans %}
    These documents govern your use of this web site. Please read them carefully.
{% endblocktrans %}
</p>

{% if request.user.is_authenticated %}
<p>
{% blocktrans %}
    If you were redirected here instead of to another page you intended to visit,
    it is probably because either these documents, or your user account, have
    recently been updated, and we need updated signatures from you before we
    proceed.
{% endblocktrans %}
</p>
{% endif %}

<table>
    <thead>
        <tr>
            {% if request.user.is_authenticated %}
                <th>{% trans "View/Sign" %}</th>
            {% else %}
                <th>{% trans "View" %}</th>
            {% endif %}
            <th>{% trans "Document Name" %}</th>
            <th>{% trans "Last Updated" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for document in current_documents %}
            <tr class="signoff-document-row-odd">
                <td class="signoff-column-min
                    {% if request.user.is_authenticated %}
                        {% if document.user_consents %}
                            signoff-document-signed
                        {% else %}
                            signoff-document-unsigned
                        {% endif %}
                    {% endif %}
                "><a href="{% url "signoff:signoff_document" id=document.id %}">
                    {% if request.user.is_authenticated %}
                        {% if document.user_consents %}
                            [{% trans "View Signed Document" %}]
                        {% else %}
                            [{% trans "Review/Signature Required" %}]
                        {% endif %}
                    {% else %}
                        [{% trans "View" %}]
                    {% endif %}
                </a></td>
                <td>{{ document.name }}</td>
                <td>{{ document.created }}</td>
            </tr>
            <tr class="signoff-document-row-even">
                <td colspan="3">
                    <p>{{ document.details }}</p>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}